### ISSUE TITLE
SQL error while loading "GameServer"

### ISSUE THREAD

**Issue by firestarter-77** [beyond-aion/aion-server#10]
### Description

**1. Everytime when starting "GameServer" i have this error in console:**

_06:36 - null
java.sql.SQLSyntaxErrorException: #42000
        at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:121)
        at com.mysql.cj.jdbc.exceptions.SQLExceptionsMapping.translateException(SQLExceptionsMapping.java:122)
        at com.mysql.cj.jdbc.ClientPreparedStatement.executeInternal(ClientPreparedStatement.java:912)
        at com.mysql.cj.jdbc.ClientPreparedStatement.executeQuery(ClientPreparedStatement.java:968)
        at com.zaxxer.hikari.pool.ProxyPreparedStatement.executeQuery(ProxyPreparedStatement.java:52)
        at com.zaxxer.hikari.pool.HikariProxyPreparedStatement.executeQuery(HikariProxyPreparedStatement.java)
        at com.aionemu.gameserver.dao.AbyssRankDAO.loadRankingListLegions(AbyssRankDAO.java:231)
        at com.aionemu.gameserver.services.abyss.AbyssRankingCache.refreshCache(AbyssRankingCache.java:54)
        at com.aionemu.gameserver.services.abyss.AbyssRankingCache.<init>(AbyssRankingCache.java:41)
        at com.aionemu.gameserver.services.abyss.AbyssRankingCache$SingletonHolder.<clinit>(AbyssRankingCache.java:130)
        at com.aionemu.gameserver.services.abyss.AbyssRankingCache.getInstance(AbyssRankingCache.java:45)
        at com.aionemu.gameserver.GameServer.main(GameServer.java:198)
06:36 - [Scheduled] Ranking update task based on cron: 0 0 0 ? * *_

============
**2. Everynigt at 00:00 have this error in GameServer console:**

_00:00 - [AbyssRankUpdateService] Executing rank update
00:00 - null
java.sql.SQLSyntaxErrorException: #42000
        at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:121)
        at com.mysql.cj.jdbc.exceptions.SQLExceptionsMapping.translateException(SQLExceptionsMapping.java:122)
        at com.mysql.cj.jdbc.ClientPreparedStatement.executeInternal(ClientPreparedStatement.java:912)
        at com.mysql.cj.jdbc.ClientPreparedStatement.executeQuery(ClientPreparedStatement.java:968)
        at com.zaxxer.hikari.pool.ProxyPreparedStatement.executeQuery(ProxyPreparedStatement.java:52)
        at com.zaxxer.hikari.pool.HikariProxyPreparedStatement.executeQuery(HikariProxyPreparedStatement.java)
        at com.aionemu.gameserver.dao.AbyssRankDAO.loadRankingListLegions(AbyssRankDAO.java:231)
        at com.aionemu.gameserver.services.abyss.AbyssRankingCache.refreshCache(AbyssRankingCache.java:54)
        at com.aionemu.gameserver.services.abyss.AbyssRankingCache.reloadRankings(AbyssRankingCache.java:81)
        at com.aionemu.gameserver.services.abyss.AbyssRankUpdateService.lambda$performUpdate$3(AbyssRankUpdateService.ja
va:44)
        at com.aionemu.commons.utils.concurrent.ExecuteWrapper.execute(ExecuteWrapper.java:32)
        at com.aionemu.commons.utils.concurrent.RunnableWrapper.run(RunnableWrapper.java:24)
        at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:572)
        at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:317)
        at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecuto
r.java:304)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
        at java.base/java.lang.Thread.run(Thread.java:1570)
00:00 - [AbyssRankUpdateService] Finished in 0 sec_

**Comment by neon-dev** [comment]
`SQLSyntaxErrorException` indicates incorrect query syntax, which is an issue on your end.
The only possible reason I can think of is that you modified this line: https://github.com/beyond-aion/aion-server/blob/2984cd672057ff36eb0b10119742af522458af34/game-server/src/com/aionemu/gameserver/dao/AbyssRankDAO.java#L41

**Comment by firestarter-77** [comment]
Now i redownload this file "game-server/src/com/aionemu/gameserver/dao/AbyssRankDAO.java" and recompile sources. not resolved. The same error.

**Comment by neon-dev** [comment]
What happens when you execute this query directly on your MySQL server?
```sh
mysql -u <user> -p -e 'SELECT l.rank_pos, l.old_rank_pos, l.id, l.name, p.race, l.level, l.contribution_points FROM legions l, legion_members lm, players p WHERE lm.rank = "BRIGADE_GENERAL" AND lm.player_id = p.id AND lm.legion_id = l.id AND l.rank_pos > 0 GROUP BY id'
```

**Comment by firestarter-77** [comment]
mysql> 'SELECT l.rank_pos, l.old_rank_pos, l.id, l.name, p.race, l.level, l.contribution_points FROM legions l, legion_members lm, players p WHERE lm.rank = "BRIGADE_GENERAL" AND lm.player_id = p.id AND lm.legion_id = l.id AND l.rank_pos > 0 GROUP BY id';
ERROR 1064 (42000):
mysql> SELECT l.rank_pos, l.old_rank_pos, l.id, l.name, p.race, l.level, l.contribution_points FROM legions l, legion_members lm, players p WHERE lm.rank = "BRIGADE_GENERAL" AND lm.player_id = p.id AND lm.legion_id = l.id AND l.rank_pos > 0 GROUP BY id;
ERROR 1046 (3D000):

**Comment by firestarter-77** [comment]
```
CREATE TABLE `legions` (
  `id` int(11) NOT NULL,
  `name` varchar(32) NOT NULL,
  `level` int(1) NOT NULL DEFAULT '1',
  `contribution_points` bigint(20) NOT NULL DEFAULT '0',
  `deputy_permission` int(11) NOT NULL DEFAULT '7692',
  `centurion_permission` int(11) NOT NULL DEFAULT '7176',
  `legionary_permission` int(11) NOT NULL DEFAULT '6144',
  `volunteer_permission` int(11) NOT NULL DEFAULT '2048',
  `disband_time` int(11) NOT NULL DEFAULT '0',
  `rank_pos` smallint(6) NOT NULL DEFAULT '0',
  `old_rank_pos` smallint(6) NOT NULL DEFAULT '0',
  `occupied_legion_dominion` int(11) NOT NULL DEFAULT '0',
  `last_legion_dominion` int(11) NOT NULL DEFAULT '0',
  `current_legion_dominion` int(11) NOT NULL DEFAULT '0',
  PRIMARY KEY (`id`),
  UNIQUE KEY `name_unique` (`name`),
  KEY `rank_pos` (`rank_pos`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;
```

**Comment by neon-dev** [comment]
> ERROR 1046 (3D000):

The test failed because no database was selected. Execute `USE <db>;` first and try again.

**Comment by firestarter-77** [comment]
mysql> USE aion_47_gs;
Database changed
mysql> "SELECT l.rank_pos, l.old_rank_pos, l.id, l.name, p.race, l.level, l.contribution_points FROM legions l, legion_members lm, players p WHERE lm.rank = "BRIGADE_GENERAL" AND lm.player_id = p.id AND lm.legion_id = l.id AND l.rank_pos > 0 GROUP BY id";
ERROR 1064 (42000):

Server version: 5.7.44-log MySQL Community Server (GPL)

**Comment by neon-dev** [comment]
> mysql> "SELECT l.rank_pos, l.old_rank_pos, l.id, l.name, p.race, l.level, l.contribution_points FROM legions l, legion_members lm, players p WHERE lm.rank = "BRIGADE_GENERAL" AND lm.player_id = p.id AND lm.legion_id = l.id AND l.rank_pos > 0 GROUP BY id";

You have to remove the outer quotation marks. If you still get the same error afterwards with no detail message, please modify your query until it works and tell us about the changes you applied to it.

**Comment by firestarter-77** [comment]
![7771](https://github.com/user-attachments/assets/34da056c-4eb6-4d2b-8720-643e1a5e6a8f)
When i add in the end "GROUP BY id", error again.

i have only 2 legions registered...
![7771](https://github.com/user-attachments/assets/64d4eea3-2558-432a-9435-10ccb03c05b5)

**Comment by neon-dev** [comment]
That makes sense. The query shouldn't need a GROUP BY clause.
It's maybe not causing issues on some other MySQL versions because it is ignored, otherwise MySQL should complain about which id to group by.
I'll have to verify but in the meantime you can remove the `GROUP BY id` from the `SELECT_RANKING_LIST_LEGIONS` constant.

**Comment by firestarter-77** [comment]
Im remove mysql v.5.7.44, and run mysql v.8.4.2, import BD. Error again

![7771](https://github.com/user-attachments/assets/6f41e881-9f55-4aff-a722-2b11a0fa002c)

**Comment by neon-dev** [comment]
Nice to see that MySQL 8 has much better error messages.
The query clearly needs to be changed in order to support v5.7+. Currently, it's only fine with older versions, as well as MariaDB.

**Comment by firestarter-77** [comment]
Thanks! I found the solution! Come back to mysql 5.7.44.
Add commandline in config "my.ini" to the section "[mysqld]" 
_"sql_mode=STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_AUTO_CREATE_USER,NO_ENGINE_SUBSTITUTION"_
No more mysql errors for me!
![7771](https://github.com/user-attachments/assets/d48f728a-c2c0-4dca-8ac7-62d5a526523a)

**Comment by neon-dev** [comment]
>  Add commandline in config "my.ini" to the section "[mysqld]"

You can pull the latest version and remove the sql_mode config from my.ini.
